import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navLinks = [
    { name: "home", href: "/" },
    { name: "contact", href: "/contact" },
    { name: "posts", href: "/posts" },
  ];

  return (
    <html className="h-screen" lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
